baseurl = "http://www.jaykhatri.me/"
title = "Jay Khatri"

theme = "coder"

languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true


[params]
    author = "Jay Khatri"
    avatarurl = "images/jay_khatri.jpeg"
    description = "Jay Khatri's personal website"

    dateformat = "January 2, 2006"

    hideCredits = false
    hideCopyright = false

    rtl = false

    # Use inverted colors
    inverted = false

    # Series see also post count
    maxSeeAlsoItems = 5

    # Custom CSS
    custom_css = []

[taxonomies]
    series = "series"


[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter"
    weight = 1
    url = "https://twitter.com/jkhatrinet"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 2
    url = "https://www.linkedin.com/in/jay-khatri-83ba5b35/"
[[params.social]]
    name = "Email"
    icon = "fas fa-envelope"
    weight = 2
    url = "mailto:jkhatri01@gmail.com"

[languages]
    [languages.en]
        languagename = "English"

        [[languages.en.menu.main]]
        name = "About"
        weight = 1
        url = "/about/"

        [[languages.en.menu.main]]
        name = "Writings"
        weight = 2
        url = "/writings/"

        [[languages.en.menu.main]]
        name = "Resume"
        weight = 3
        url = "/files/jay_khatri_cv.pdf"

        [[languages.en.menu.main]]
        name = "Project Aapdi Hawa"
        weight = 4

        [[languages.en.menu.main]]
        name = "About"
        parent = "Project Aapdi Hawa"
        url = "/aapdi_hawa/"

        [[languages.en.menu.main]]
        name = "Reports"
        parent = "Project Aapdi Hawa"
        url = "/aapdi_hawa_reports/"

